apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    url: http://tempo-simplest-query-frontend.my-tempo:3200
    jsonData:
      nodeGraph:
        enabled: true
      search:
        filters:
          - id: service-name
            operator: "="
            scope: resource
            tag: service.name
          - id: span-name
            operator: "="
            scope: span
            tag: name
        hide: true
        tags:
          - key: service.name
            value: service_name
    readOnly: false
