# cluster.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # TODO: If you do not want access from outside clusters, comment this out.
  extraPortMappings:
    - containerPort: 30000
      hostPort: 8081
      protocol: TCP
    - containerPort: 30001
      hostPort: 3001
      protocol: TCP
    - containerPort: 30002
      hostPort: 3002
      protocol: TCP
    - containerPort: 30003
      hostPort: 3003
      protocol: TCP
    - containerPort: 30004
      hostPort: 3004
      protocol: TCP
    - containerPort: 30005
      hostPort: 3005
      protocol: TCP
    - containerPort: 30006
      hostPort: 3006
      protocol: TCP
    - containerPort: 30007
      hostPort: 3007
      protocol: TCP
    - containerPort: 30008
      hostPort: 3008
      protocol: TCP
    - containerPort: 30009
      hostPort: 3009
      protocol: TCP
    - containerPort: 30010
      hostPort: 3010
      protocol: TCP
- role: worker
- role: worker
- role: worker
