apiVersion: v1
kind: Namespace
metadata:
  name: my-grafana
---
apiVersion: v1
kind: Namespace
metadata:
  name: my-tempo
---
apiVersion: v1
kind: Namespace
metadata:
  name: mockserver
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: loadtest
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    istio-injection: enabled
